name: Neovim Config Validation

on:
  push:
    paths:
      - 'lua/**'
      - 'init.lua'
      - 'scripts/check_neovim.sh'
      - '.github/workflows/nvim-config-check.yml'
  pull_request:
    paths:
      - 'lua/**'
      - 'init.lua'
      - 'scripts/check_neovim.sh'
      - '.github/workflows/nvim-config-check.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  validate-config:
    name: Validate Neovim Configuration
    runs-on: ubuntu-latest
    env:
      CI: true
      GITHUB_ACTIONS: true
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacheck
        run: luarocks install luacheck
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
          
      - name: Install Packer
        run: |
          git clone --depth 1 https://github.com/wbthomason/packer.nvim\
           ~/.local/share/nvim/site/pack/packer/start/packer.nvim
      
      - name: Setup core plugins (without PackerSync)
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/packer/start
          
          # Clone key plugins directly instead of using PackerSync which can hang
          git clone --depth 1 https://github.com/neovim/nvim-lspconfig ~/.local/share/nvim/site/pack/packer/start/nvim-lspconfig
          git clone --depth 1 https://github.com/williamboman/mason.nvim ~/.local/share/nvim/site/pack/packer/start/mason.nvim
          git clone --depth 1 https://github.com/williamboman/mason-lspconfig.nvim ~/.local/share/nvim/site/pack/packer/start/mason-lspconfig.nvim
          git clone --depth 1 https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/site/pack/packer/start/plenary.nvim
          git clone --depth 1 https://github.com/nvim-telescope/telescope.nvim ~/.local/share/nvim/site/pack/packer/start/telescope.nvim
          git clone --depth 1 https://github.com/nvim-treesitter/nvim-treesitter ~/.local/share/nvim/site/pack/packer/start/nvim-treesitter
          
          echo "Core plugins installed directly"
      
      - name: Validate Mason module separately
        timeout-minutes: 2
        run: |
          # Create a simple script to check Mason
          cat > check_mason.lua << 'EOF'
          local success, mason = pcall(require, "mason")
          if success then
            print("✅ Mason module loaded successfully")
          else
            print("❌ Mason module failed to load: " .. tostring(mason))
            os.exit(1)
          end
          
          local success2, mason_lspconfig = pcall(require, "mason-lspconfig")
          if success2 then
            print("✅ Mason-lspconfig module loaded successfully")
          else
            print("❌ Mason-lspconfig module failed to load")
          end
          
          -- Try to see if mason setup will work
          pcall(function()
            mason.setup()
            print("✅ Mason setup ran successfully")
          end)
          
          vim.cmd("qa!")
          EOF
          
          # Run with timeout
          nvim --headless -c "luafile check_mason.lua" || echo "Mason check completed with possible warnings"
      
      - name: Make check script executable
        run: chmod +x ./scripts/check_neovim.sh
      
      - name: Run Neovim configuration check
        timeout-minutes: 5
        run: ./scripts/check_neovim.sh
          
      - name: Summary
        run: echo "✅ Neovim configuration validation completed successfully!" 