name: Neovim Config Validation

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  validate-config:
    name: Validate Neovim Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Lua
        uses: leafo/gh-actions-lua@v9
        with:
          luaVersion: "5.1"
      
      - name: Setup luarocks
        uses: leafo/gh-actions-luarocks@v4
      
      - name: Install luacheck
        run: luarocks install luacheck
      
      - name: Run luacheck 
        run: |
          luacheck lua/ --no-max-line-length --no-max-comment-line-length
      
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: stable
          
      - name: Install Packer
        run: |
          git clone --depth 1 https://github.com/wbthomason/packer.nvim\
           ~/.local/share/nvim/site/pack/packer/start/packer.nvim
          
      - name: Validate init.lua syntax
        run: nvim --headless -c 'lua print("Checking init.lua syntax")' -c 'q' || echo "Init.lua has syntax errors"
      
      - name: Check if plugins can be loaded
        run: |
          mkdir -p ~/.local/share/nvim/site/pack/packer/opt
          nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerSync' || true
          echo "Plugin installation attempted"
          
      - name: Check if configuration loads without errors
        run: |
          nvim --headless --noplugin -u init.lua -c "lua vim.health.report()" -c "q" > health_check.txt 2>&1 || true
          cat health_check.txt
          ! grep -q "Error" health_check.txt || (echo "Errors found in configuration" && exit 1)
          
      - name: Check LSP configuration
        run: |
          # Verify LSP config files exist and have proper syntax
          [ -d "./lua/user/lsp" ] || (echo "LSP configuration directory missing" && exit 1)
          find ./lua/user/lsp -name "*.lua" -exec nvim --headless -c "luafile {}" -c "q" \; || (echo "LSP config has errors" && exit 1)
          
      - name: Summary
        run: echo "✅ Neovim configuration validation completed successfully!" 